name: universal_html
version: 1.1.12
description:
  Cross-platform 'dart:html' that works in the browser, Dart VM, and Flutter.
homepage: https://github.com/terrier989/universal_html

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  async: ^2.3.0
  charcode: ^1.1.0
  collection: ^1.14.0
  csslib: ^0.16.0
  html: ^0.14.0
  meta: ^1.1.0
  typed_data: ^1.1.0
  universal_io:
    git:
      url: https://github.com/dint-dev/universal_io
      path: packages/universal_io
  xml: ^3.5.0
  zone_local: ^0.1.0

dev_dependencies:
  pedantic: ^1.9.0
  stream_channel: ^2.0.0
  test: ^1.8.0
